name: Test Suite

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Update coverage badge, skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.LIFEMD_OPS_BOT_PAT }}

      # Set PHP version
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Validate composer.json
      - name: Validate composer.json and composer.lock
        run: composer validate

      # Run composer install
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run PHP Stan
      - name: PHPStan
        run: vendor/bin/phpstan analyse src --memory-limit=2G

      # Run PHP Unit
      - name: PHPUnit
        run: vendor/bin/phpunit --verbose --coverage-text

      # Add coverage badge
      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_badge_path: ./.coverage/coverage.svg
          report: ./.coverage/clover.xml
          report_type: clover
          commit_message: "[Update coverage badge, skip ci]"
